<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>Mapsicle.Caching</PackageId>
    <Description>Caching integration for Mapsicle - Cache mapped results with IMemoryCache and IDistributedCache support</Description>
    <PackageTags>mapper;mapping;caching;redis;memoryache;automapper-alternative</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Mapsicle.Fluent\Mapsicle.Fluent.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="8.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

</Project>
